"""create_whatsapp_configs_table

Revision ID: 3ddf2b07e84b
Revises: e5d86cac91b3
Create Date: 2026-07-24 16:17:17.965652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ddf2b07e84b'
down_revision: Union[str, None] = 'e5d86cac91b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('waba_id', sa.String(length=100), nullable=False),
    sa.Column('phone_number_id', sa.String(length=100), nullable=False),
    sa.Column('encrypted_access_token', sa.String(length=500), nullable=False),
    sa.Column('webhook_verify_token', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_configs_id'), 'whatsapp_configs', ['id'], unique=False)
    op.create_index(op.f('ix_whatsapp_configs_tenant_id'), 'whatsapp_configs', ['tenant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_configs_tenant_id'), table_name='whatsapp_configs')
    op.drop_index(op.f('ix_whatsapp_configs_id'), table_name='whatsapp_configs')
    op.drop_table('whatsapp_configs')
    # ### end Alembic commands ###